[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4F5E6B"
base = "dark"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#242424"
textColor = "#e6e6e6"
font = "sans serif"
